// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	DeviceReading
	DeviceStatus
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeviceReading struct {
	SensorType    string  `protobuf:"bytes,1,opt,name=sensor_type,json=sensorType" json:"sensor_type,omitempty"`
	Timestamp     int64   `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	SensorReading float32 `protobuf:"fixed32,3,opt,name=sensor_reading,json=sensorReading" json:"sensor_reading,omitempty"`
	Unit          string  `protobuf:"bytes,4,opt,name=unit" json:"unit,omitempty"`
	SerialNumber  string  `protobuf:"bytes,5,opt,name=serial_number,json=serialNumber" json:"serial_number,omitempty"`
}

func (m *DeviceReading) Reset()                    { *m = DeviceReading{} }
func (m *DeviceReading) String() string            { return proto.CompactTextString(m) }
func (*DeviceReading) ProtoMessage()               {}
func (*DeviceReading) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DeviceReading) GetSensorType() string {
	if m != nil {
		return m.SensorType
	}
	return ""
}

func (m *DeviceReading) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *DeviceReading) GetSensorReading() float32 {
	if m != nil {
		return m.SensorReading
	}
	return 0
}

func (m *DeviceReading) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *DeviceReading) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

type DeviceStatus struct {
	SerialNumber string `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber" json:"serial_number,omitempty"`
	DeviceStatus bool   `protobuf:"varint,2,opt,name=device_status,json=deviceStatus" json:"device_status,omitempty"`
}

func (m *DeviceStatus) Reset()                    { *m = DeviceStatus{} }
func (m *DeviceStatus) String() string            { return proto.CompactTextString(m) }
func (*DeviceStatus) ProtoMessage()               {}
func (*DeviceStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeviceStatus) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *DeviceStatus) GetDeviceStatus() bool {
	if m != nil {
		return m.DeviceStatus
	}
	return false
}

func init() {
	proto.RegisterType((*DeviceReading)(nil), "DeviceReading")
	proto.RegisterType((*DeviceStatus)(nil), "DeviceStatus")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xb1, 0x4a, 0xc7, 0x30,
	0x10, 0xc6, 0xc9, 0xbf, 0x55, 0xec, 0xd9, 0x38, 0x64, 0xca, 0x20, 0x58, 0x2a, 0x42, 0x27, 0x17,
	0x5f, 0xc1, 0xd9, 0x21, 0x3a, 0xb8, 0x95, 0xd4, 0x1e, 0x25, 0x60, 0xd2, 0x90, 0x4b, 0x85, 0xbe,
	0x94, 0xcf, 0x28, 0x5e, 0x14, 0x85, 0x6e, 0xe1, 0x97, 0xfb, 0x7d, 0xf7, 0x71, 0x20, 0x3d, 0x12,
	0xd9, 0x05, 0xef, 0x63, 0x5a, 0xf3, 0xda, 0x7f, 0x0a, 0x90, 0x8f, 0xf8, 0xe1, 0xde, 0xd0, 0xa0,
	0x9d, 0x5d, 0x58, 0xd4, 0x0d, 0x5c, 0x12, 0x06, 0x5a, 0xd3, 0x98, 0xf7, 0x88, 0x5a, 0x74, 0x62,
	0x68, 0x0c, 0x14, 0xf4, 0xb2, 0x47, 0x54, 0xd7, 0xd0, 0x64, 0xe7, 0x91, 0xb2, 0xf5, 0x51, 0x9f,
	0x3a, 0x31, 0x54, 0xe6, 0x0f, 0xa8, 0x3b, 0xb8, 0xfa, 0xd1, 0x53, 0x09, 0xd4, 0x55, 0x27, 0x86,
	0x93, 0x91, 0x85, 0xfe, 0x6e, 0x51, 0x50, 0x6f, 0xc1, 0x65, 0x5d, 0x73, 0x3c, 0xbf, 0xd5, 0x2d,
	0x48, 0xc2, 0xe4, 0xec, 0xfb, 0x18, 0x36, 0x3f, 0x61, 0xd2, 0x67, 0xfc, 0xd9, 0x16, 0xf8, 0xc4,
	0xac, 0x7f, 0x85, 0xb6, 0xf4, 0x7d, 0xce, 0x36, 0x6f, 0x74, 0x94, 0xc4, 0x51, 0xfa, 0x1e, 0x9a,
	0x59, 0x1a, 0x89, 0x2d, 0xae, 0x7d, 0x61, 0xda, 0xf9, 0x5f, 0xd2, 0x74, 0xce, 0x17, 0x79, 0xf8,
	0x0a, 0x00, 0x00, 0xff, 0xff, 0xdd, 0x1b, 0xf8, 0xa3, 0x22, 0x01, 0x00, 0x00,
}
